import React from 'react'
import Footer from './Footer'
import Header from './Header'
import Head from 'next/head'
import Hero from './Hero'

const Layout = ({children}) => {
  return (
    <>
      <Head>
        <title>Money Gram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
    </>
  )
}

export default Layout
